### ISSUE TITLE
Document deployment of solr configs in solr cloud

### ISSUE THREAD

**Issue by tampakis** [pulibrary/pul-the-hard-way#34]
Update: closing this ticket should just be a matter of pointing to the pul_solr repository

@eliotjordan these were the notes I kept for zipping and uploading the config sets for solr cloud. We should automate the process:
```
To replace configsets:
Create zips of the configsets in programmatic fashion based on directory name within solr_configs
Upload replacement version appended with tmp i.e.:
curl -X POST --header "Content-Type:application/octet-stream" --data-binary @pulmap.zip "http://localhost:8983/solr/admin/configs?action=UPLOAD&name=pulmap-tmp”
Replace all of the collections that use the old version with the tmp version i.e.:
http://localhost:8983/solr/admin/collections?action=MODIFYCOLLECTION&collection=pulmap&collection.configName=pulmap-tmp
Delete old configs:
http://localhost:8983/solr/admin/configs?action=DELETE&name=pulmap
Upload new configs without tmp
curl -X POST --header "Content-Type:application/octet-stream" --data-binary @pulmap.zip "http://localhost:8983/solr/admin/configs?action=UPLOAD&name=pulmap”
Replace all collections with original configset name:
http://localhost:8983/solr/admin/collections?action=MODIFYCOLLECTION&collection=pulmap&collection.configName=pulmap
Delete all tmp config sets:
http://localhost:8983/solr/admin/configs?action=DELETE&name=pulmap-tmp



(cd /solr/pul_solr/current/solr_configs/orangelight/conf && zip -r - *) > orangelight.zip
(cd /solr/pul_solr/current/solr_configs/pulmap/conf && zip -r - *) > pulmap.zip
(cd /solr/pul_solr/current/solr_configs/figgy/conf && zip -r - *) > figgy.zip
(cd /solr/pul_solr/current/solr_configs/lae-blacklight/conf && zip -r - *) > lae-blacklight.zip
(cd /solr/pul_solr/current/solr_configs/dpul-blacklight/conf && zip -r - *) > dpul-blacklight.zip
curl -X POST --header "Content-Type:application/octet-stream" --data-binary @orangelight.zip "http://localhost:8983/solr/admin/configs?action=UPLOAD&name=orangelight"

curl -X POST --header "Content-Type:application/octet-stream" --data-binary @pulmap.zip "http://localhost:8983/solr/admin/configs?action=UPLOAD&name=pulmap"

curl -X POST --header "Content-Type:application/octet-stream" --data-binary @figgy.zip "http://localhost:8983/solr/admin/configs?action=UPLOAD&name=figgy"

curl -X POST --header "Content-Type:application/octet-stream" --data-binary @lae-blacklight.zip "http://localhost:8983/solr/admin/configs?action=UPLOAD&name=lae-blacklight"

curl -X POST --header "Content-Type:application/octet-stream" --data-binary @dpul-blacklight.zip "http://localhost:8983/solr/admin/configs?action=UPLOAD&name=dpul-blacklight"
```

**Comment by hackmastera** [comment]
From looking around, it seems like you can just update the config set directly (i.e. without the `tmp` workaround), as long as you reload the collection afterward. Did y'all try it that way? @tampakis @eliotjordan 

https://lucene.apache.org/solr/guide/6_6/collections-api.html#CollectionsAPI-reload

**Comment by escowles** [comment]
@hackmastera How do you update a ConfigSet?  I don't see an update command in https://lucene.apache.org/solr/guide/6_6/configsets-api.html  — but if it's possible, it would be much nicer than the process we have now.

**Comment by hackmastera** [comment]
@escowles I guess I am equating upload with update. The process in the documentation suggests that you download, make changes, and then upload again:

https://lucene.apache.org/solr/guide/6_6/using-zookeeper-to-manage-configuration-files.html#UsingZooKeepertoManageConfigurationFiles-ManagingYourSolrCloudConfigurationFiles

**Comment by hackmastera** [comment]
In our case I guess we would trust what we have in git rather than downloading from the server.

**Comment by escowles** [comment]
Yes, I think downloading from Git makes more sense than fetching from Zk.  But I do think that "upload" means creating a new ConfigSet.

One change we might consider over the process outlined above would be to number the configs (or use Git commit hash?), so the process would be:
1. Create zips of the configsets in programmatic fashion based on directory name within solr_configs
2. Upload new version appended with version number i.e.:
`curl -X POST --header "Content-Type:application/octet-stream" --data-binary @pulmap.zip "http://localhost:8983/solr/admin/configs?action=UPLOAD&name=pulmap-2"`
3. Update all of the collections that use the old version with the new version i.e.:
`http://localhost:8983/solr/admin/collections?action=MODIFYCOLLECTION&collection=pulmap&collection.configName=pulmap-2`
4. Delete old configs:
`http://localhost:8983/solr/admin/configs?action=DELETE&name=pulmap-1`

**Comment by hackmastera** [comment]
discussion such as https://stackoverflow.com/a/40722097/341514 suggests you can upload it with the same name and the server will replace the file. it at least seems worth trying if we haven't tried it yet.

**Comment by eliotjordan** [comment]
@hackmastera That totally works! Brilliant. 💯 

In `/opt/solr/bin` run `./solr zk -upconfig -d path/to/pul_solr/solr_configs/lae-blacklight -n lae` then reload the collections that use that configset.

**Comment by escowles** [comment]
That's great news — thanks for digging that up @hackmastera !

**Comment by hackmastera** [comment]
@eliotjordan do we run that from a zookeeper machine or from a solr machine or either?
