### ISSUE TITLE
add information on what a SAN means

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/pul-the-hard-way#70]

**Comment by bess** [comment]
![Screen Shot 2021-03-18 at 3 22 18 PM](https://user-images.githubusercontent.com/65608/111685100-e5fd7200-87fd-11eb-951a-e5063f475ddf.png)

**Comment by kayiwa** [comment]
create a new file by running this command on `echo`

**Comment by kayiwa** [comment]
add the files to princeton_ansible path
