### ISSUE TITLE
Broken link to Ubuntu release on prerequisites.md

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/pul-the-hard-way#9]
Following the link gives a 404. Perhaps:

https://wiki.ubuntu.com/XenialXerus/ReleaseNotes?_ga=2.73655378.1765254830.1513346133-777330587.1511993419

**Comment by kayiwa** [comment]
Given you the PR

https://github.com/pulibrary/pul-the-hard-way/pull/10
